#!/usr/bin/env python3
"""Generate the Objective-C base64 include used by the embedded Web console."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Web" / "console.html"
OUTPUT = ROOT / "Source" / "DHWebConsoleBase64.inc"


def generated_text() -> str:
    encoded = base64.b64encode(SOURCE.read_bytes()).decode("ascii")
    lines = ["// Generated by Tools/embed_web.py. Do not edit directly.",
             "static NSString * const kDHWebConsoleBase64 ="]
    for offset in range(0, len(encoded), 120):
        suffix = ";" if offset + 120 >= len(encoded) else ""
        lines.append(f'@"{encoded[offset:offset + 120]}"{suffix}')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated include is stale")
    args = parser.parse_args()
    expected = generated_text()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
